### ISSUE TITLE
Release Offline Version To Download On Github Releases

### ISSUE THREAD

**Issue by trymeouteh** [iancoleman/slip39#22]
Please release an offline HTML version to download on Github just like that is done for BIP39 with signatures

https://github.com/iancoleman/bip39/releases

**Comment by iancoleman** [comment]
Good idea thanks. See https://github.com/iancoleman/slip39/releases/tag/0.0.3

**Comment by trymeouteh** [comment]
Thank you! Please maintain the releases when you update the project.
